NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.backup.ps26237.local-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.backup.ps26237.local-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.backup.ps26237.local-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.backup.ps26237.local-cert.pem
    OrganizationalUnitIdentifier: orderer
